fix arm64 gdpy3-app, lost so files and MATPLOTLIBDATA
1. gdpy3-app/img2sixel: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.22' not found (required by gdpy3-app/libgnutls.so.30)
2. libresolv.so.2: symbol __resolv_context_get_preinit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
3. gdpy3-app/tkinter/__init__.pyc in <module>()
   ImportError: gdpy3-app/libX11.so.6: undefined symbol: xcb_poll_for_reply64, please install the python3-tk package
4. mpl 2.0.0: pyinstaller No such file or directory: '/usr/share/matplotlib/mpl-data/stylelib'